# Tell Jekyll the name of our site
name: iconfont

# What version of markdown to use
markdown: kramdown

# (username.github.io/project-name/). Here's what to do:
# In _config.yml, set the baseurl option to /project-name -- note the leading slash and the absence of a trailing slash.
baseurl: /iconfont

# When referencing JS or CSS files, do it like this:
# {{ site.baseurl }}/path/to/css.css -- note the slash immediately following the variable (just before "path").

# When doing permalinks or internal links, do it like this:
# {{ site.baseurl }}{{ post.url }} -- note that there is no slash between the two variables.

# Finally, if you'd like to preview your site before committing/deploying using jekyll serve,
# be sure to pass an empty string to the --baseurl option, so that you can view everything at
# localhost:4000 normally (without /project-name getting in there to muck everything up): jekyll serve --baseurl ''

# This way you can preview your site locally from the site root on localhost, but when GitHub
# generates your pages from the gh-pages branch all the URLs will start with /project-name and resolve properly.

# Site-wide defaults
# The defaults key holds an array of scope/values pairs that define what defaults
# should be set for a particular file path, and optionally, a file type in that path.
defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "pages"
        values:
            layout: "default"